using Test
using LogClustering

@testset "LogClustering.jl" begin
    include("test_KATE.jl")
    include("test_deepkate.jl")
    include("test_anomaly.jl")
    include("test_anomaly_sequence.jl")
    include("test_value_novelty.jl")
    include("test_seqlstm.jl")
    include("test_transformer.jl")
    include("test_vqvae.jl")
    include("test_simcse.jl")
    include("test_denoising_ae.jl")
    include("test_softkate.jl")
    include("test_framing.jl")
    include("test_preproc.jl")
    include("test_featurise.jl")
    include("test_episodes.jl")
    include("test_baselines.jl")
    include("test_eval.jl")
    include("test_compression.jl")
    include("test_cv.jl")
    include("test_cluster.jl")
    include("test_drain.jl")
    include("test_canonical.jl")
    include("test_postproc.jl")
    include("test_persistence.jl")
    include("test_autotune.jl")
    include("test_rca.jl")
    include("test_rules.jl")
    include("test_stream.jl")
    include("test_sinks_webhook.jl")
    include("test_memory_sqlite.jl")
    include("test_stream_e2e.jl")
    include("test_memory_e2e.jl")
    include("test_cli.jl")
    include("test_ad.jl")
    include("test_rust.jl")
end
